name: Deploying main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, nisar-social-vm]

    env:
      PM2_PROCESS_NAME: "nisar-social"
      PORT: 3010
      NODE_VERSION: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js app
        run: npm run build

      - name: Install pm2 globally
        run: npm install -g pm2

      - name: Start or Restart the Next.js Application with PM2
        run: |
          pm2 restart "$PM2_PROCESS_NAME" || PORT=$PORT pm2 start "npm start" --name "$PM2_PROCESS_NAME"
          pm2 save
